### ISSUE TITLE
Does driver conform to REP-103?

### ISSUE THREAD

**Issue by babazaroni** [yoshito-n-students/bno055_usb_stick#10]
Just a question, does the driver output according to REP-103?  Specifically, does the linear acceleration conform to ENU, east-north-up?

I don't know whether the data from the stick is REP-103 formatted, but maybe the driver converts it to REP-103.

**Comment by yoshito-okada** [comment]
Yes.  The coordinate system is device's default (right-handed) and ROS's standard units defined by REP-103 are used in published messages.
