### ISSUE TITLE
Error- Incorrect Bosh IMU device response

### ISSUE THREAD

**Issue by mrtpk** [yoshito-n-students/bno055_usb_stick#14]
Thanks for sharing this code. I was trying to connect bno055 with ROS indigo ubuntu 14.04LTS and got the error `Incorrect Bosh IMU device response`.  I found that while reading from dev the byte array length is zero. Can you tell me how to resolve this error? I'm using bno055 with red pcb.

**Comment by yoshito-okada** [comment]
I have never seen that error.  Did you see the words "Incorrect Bosh IMU device response" on your console?   These words are not implemented in my code so I am wondering how they came up.

**Comment by mrtpk** [comment]
Thanks for pointing it out. I'm very sorry about this. You are correct and his issue should not have been raised here. I apologize.
