### ISSUE TITLE
[ERROR] []: start: open: Permission denied

### ISSUE THREAD

**Issue by anleger92** [yoshito-n-students/bno055_usb_stick#7]
Hi,

I have got an BNO055 USB Stick and want to use it with ubuntu 16.04 and ros kinetic.
I installed the package and tried to run the node. But when I run the node I get the following output:

[ERROR] [1526481970.305344177]: start: open: Permission denied

I didn't install any other driver or updated the firmware. I just plugged in the usb stick and installed the package. What else do I have to do, when I want to run this node?

Thank you in advance.

Best wishes
anleger

**Comment by BillWSY** [comment]
The easiest fix will be running the driver with `sudo`.

The next easiest method will be `sudo chmod 666 /dev/ttyACM0`.

The right thing to do is `sudo usermod -aG dialout $USER`

The other thing you can do is to set up a `udev` rule to create correct permission for `/dev/ttyACM0`

**Comment by yoshito-okada** [comment]
Agree with @BillWSY .  What I always do is the third one.   Doing once after installing Ubuntu is enough.

**Comment by anleger92** [comment]
Hey, 
thank you for your answers.

I tried typing `sudo cmod 666 /dev/ttyACM0` and it worked. But I need to type it every time I plug in the usb imu stick.

Then I tried to create a rule by creating a rule file in `/etc/udev/rules.d`
and applied following rule in the created rule file:
`SUBSYSTEMS=="usb", ATTRS{idVendor}=="0x152a", ATTRS{idProduct}=="0x80c1", MODE:="0666"`

With this rule the imu stick worked once. Now when I run the node I get following output:
`[ERROR] []: start: open: Device or resource busy`

EDIT: In the case I plug out the imu stick and replug it in, I get this error. Is it possipble that I have to restart roscore in this case?

How can I solve this?

Thank you again :)

**Comment by yoshito-okada** [comment]
Your udev rule may miss a GROUP attribute.  Or try the 3rd proposal in @BillWSY 's post.

**Comment by anleger92** [comment]
I tried `sudo usermod -aG dialout $USER` but somehow it said, that permission was still denied.
Do I have to modify anything in this line?

**Comment by yoshito-okada** [comment]
`sudo usermod -aG dialout $USER` should work on ubuntu 16.  Reboot the computer or google "ubuntu 16 add user to group dialout".

**Comment by anleger92** [comment]
it works, thank you for your help!
