### ISSUE TITLE
Run directions please?

### ISSUE THREAD

**Issue by babazaroni** [yoshito-n-students/bno055_usb_stick#9]
Would be nice to see run directions in the readme.

I used:  `rosrun bno055_usb_stick bno055_usb_stick_node` but got back error message

`[ERROR] [1527981048.145777140]: handleWaitResponse: End of file`

I have  updated the firmware to the latest: `BNO_Firmware_0.3.2.0.hex`.  I also updated the controller firmware to `BNOinUSBStick_V1.4.fwu3`.

The stick works fine in Development Desktop 2.0.

The stick is at port `ttyACM0`.

**Comment by babazaroni** [comment]
After doing a few things like turning device off and on, rebooting, the node is running.

Thanks for the package.  Looks well written.

**Comment by yoshito-okada** [comment]
good to hear that.
